# Configuration for file paths
paths:
  chroma_db: "./chroma_db" 
  processed_files: "./processed_files"

# Model names for different agents
models:
  intent: "mistral:v0.3" 
  router: "mistral-small3.2" #"qwen3:14b"
  reasoning: "mistral-small3.2" #"qwen3:14b" 
  summarizer: "mistral:v0.3"
  general: "mistral:v0.3"
  final_answer: "mistral:v0.3"

# Application thresholds
settings:
  relevance_threshold: 0.1