# Configuration for file paths
paths:
  chroma_db: "./chroma_db" 
  processed_files: "./processed_files"

# Model names for different agents
models:
  intent: "models--mistralai--Mistral-7B-v0.3" #"mistral:latest"
  router: "models--mistralai--Mistral-Small-3.2-24B-Instruct-2506" #"qwen3:14b"
  reasoning: "models--mistralai--Mistral-Small-3.2-24B-Instruct-2506" #"qwen3:14b" 
  summarizer: "models--mistralai--Mistral-7B-v0.3"
  general: "models--mistralai--Mistral-7B-v0.3"
  final_answer: "models--mistralai--Mistral-7B-v0.3"

# Application thresholds
settings:
  relevance_threshold: 0.1